version: '3.8'
services:
  postgres:
    platform: linux/arm64
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./persistence/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./persistence/schema:/db_scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: server
    env_file:
      - .env
    ports:
      - "3006:3006"
    depends_on:
      postgres:
        condition: service_healthy